name: Build
on:
  push:
    branches:
      - '*'
  workflow_dispatch:
jobs:
  build:
    name: ğŸ‘· Build
    runs-on: ubuntu-latest
    steps:
    - name: ğŸ›‘ Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.10.1
      with:
        access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: â¬‡ï¸ Check out
      uses: actions/checkout@v3.1.0
      with:
        fetch-depth: 1
    - run: echo "Building"
  docker-build:
    name: ğŸ“¦ Docker build
    runs-on: ubuntu-latest
    needs:
    - "build"
    steps:
    - name: â¬‡ï¸ Check out
      uses: actions/checkout@v3.1.0
      with:
        fetch-depth: 1
    - name: ğŸ‹ Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.PAT }} # `PAT` is a secret that contains your Personal Access Token with `write:packages` scope
    - name: ğŸ‹ Build and push docker image
      uses: docker/build-push-action@v3.1.1
      with:
        context: .
        file: Dockerfile.2stage
        platforms: linux/amd64
        push: true
        tags: |
          ghcr.io/paulescu/taxi-data-api-python:${{ github.sha }}
#   deploy-preview:
#     name: ğŸ§ª Deploy / Preview
#     runs-on: ubuntu-latest
#     needs:
#     - "docker-build"
#     if: github.ref != 'refs/heads/main'
#     environment: preview
#     steps:
#     - name: â¬‡ï¸ Check out
#       uses: actions/checkout@v3.1.0
#       with:
#         fetch-depth: 1
#     - name: ğŸ§ª Deploy / Preview
#       uses: gimlet-io/gimlet-artifact-shipper-action@v0.9.0
#       with:
#         DEPLOY: "true"
#         ENV: "preview"
#         APP: "gais"
#       env:
#         GIMLET_SERVER: ${{ secrets.GIMLET_SERVER }}
#         GIMLET_TOKEN: ${{ secrets.GIMLET_TOKEN }}
#   deploy-staging:
#     name: ğŸš€ Deploy / Staging
#     runs-on: ubuntu-latest
#     needs:
#     - "docker-build"
#     if: github.ref == 'refs/heads/main'
#     environment: staging
#     steps:
#     - name: â¬‡ï¸ Check out
#       uses: actions/checkout@v3.1.0
#       with:
#         fetch-depth: 1
#     - name: ğŸš€ Deploy / Staging
#       uses: gimlet-io/gimlet-artifact-shipper-action@v0.9.0
#       with:
#         DEPLOY: "true"
#         ENV: "staging"
#         APP: "gais"
#       env:
#         GIMLET_SERVER: ${{ secrets.GIMLET_SERVER }}
#         GIMLET_TOKEN: ${{ secrets.GIMLET_TOKEN }}
  deploy-production:
    name: ğŸ§‘â€ğŸš€ Deploy / Production
    runs-on: ubuntu-latest
    needs:
    - "docker-build"
    if: github.ref == 'refs/heads/main'
    environment: production
    steps:
    - name: â¬‡ï¸ Check out
      uses: actions/checkout@v3.1.0
      with:
        fetch-depth: 1
    - name: ğŸš€ Deploy / Production
      uses: gimlet-io/gimlet-artifact-shipper-action@v0.9.0
      with:
        DEPLOY: "true"
        ENV: "production"
        APP: "gais"
      env:
        GIMLET_SERVER: ${{ secrets.GIMLET_SERVER }}
        GIMLET_TOKEN: ${{ secrets.GIMLET_TOKEN }}